### ISSUE TITLE
Upgrade configuration to be compatible with react-dev 0.2.x

### ISSUE THREAD

**Issue by mauleb** [JBKLabs/example-react-project#7]
At the moment, the example react project has the following known problems:

* it installs `eslint-config` rather than letting `react-dev` handle it
* it does not declare an `eject` script
* it does not provide a path for `jbk-scripts lint`
* it has an invalid value for `package.json#main`
* it is using an old version of `react-dev`

**Comment by joshytaco** [comment]
Solved in #9
